version: '3'

services:
  mango:
    container_name: mango
    restart: unless-stopped
    mem_limit: 2048m
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    expose:
      - ${PORT}
    ports:
      - "${PORT}:9000"
    volumes:
      - ${MAIN_DIRECTORY_PATH}:/root/mango
      - ${CONFIG_DIRECTORY_PATH}:/root/.config/mango
      - ${LIBRARY_PATH}:/root/library
